### ISSUE TITLE
The robot does not start to move after hitting the point

### ISSUE THREAD

**Issue by JiaWenHa** [hikashi/multi-robot-rrt-exploration-noetic#1]
ubuntu20.04 +ROS Noetic.
The robot does not start to move after hitting the point.

**Comment by hikashi** [comment]
Hi, this is the same problem found in the original work I believe. 
Also, the movebase and turtlebot3 localization I provided is not highly optimized. Therefore, it could be the problem of it. 
My work is merely convert it to ROS Noetic and help the community to run 2D exploration. Hope you understand.
