### ISSUE TITLE
The robot isn't spawned into the created world . It doesnt seem to work.

### ISSUE THREAD

**Issue by Daviesss** [hikashi/multi-robot-rrt-exploration-noetic#10]

**Comment by Daviesss** [comment]
Every time a  created world is added to the launch file . The robot doesn't get spawned into the world .

**Comment by hikashi** [comment]
Can you elaborate more? like what is the exact problem?
It seem like a turtlebot simulation problem. 
Can you try to run the sample turtlebot program?

**Comment by Daviesss** [comment]
I got it solved . In the launch file the "gui" parameter is meant to be set to true. Do you think a pull request can be sent by me for changes? 


Regards.

**Comment by Daviesss** [comment]
Another problem is "waffle_pi" only works for the exploration . But when I export "burger" there is a high redundant in the tf . Is there a specific file to make changes to get "burger" version up for exploration for multiple robot?

**Comment by hikashi** [comment]
> I got it solved . In the launch file the "gui" parameter is meant to be set to true. Do you think a pull request can be sent by me for changes?
> 
> Regards.

I think it depends. For faster simulation speed, setting it to false might help with faster simulation if your simulation environment is configured properly.

Lastly, the whole simulation is setup up using waffle pi. If you need other robot models, then you have to configure yourself.

**Comment by Daviesss** [comment]
So is it possible to just export turtle bot burger . I keep having a redundant error "Tf repeated data ignoring data with redundant timestamp from base_footprint at time 59" even after configuration.

**Comment by Daviesss** [comment]
Problem solved . Will send a pull request on integration of burger for multi robot rrt .

**Comment by Daviesss** [comment]
>  So is it possible to just export turtle bot burger . I keep having a redundant error "Tf repeated data ignoring data with redundant timestamp from base_footprint at time 59" even after configuration.

Problem solved . Will send a pull request on integration of burger for multi robot rrt exploration.
