### ISSUE TITLE
Running the code on robot

### ISSUE THREAD

**Issue by mmsh28** [hikashi/multi-robot-rrt-exploration-noetic#2]
Hello, 
the simulation is working excellently, yet how can I run this code on a physical robot, it is not working. 
Thanks in advance.

**Comment by hikashi** [comment]
Hi, this repository is dedicated to converting the RRT exploration from ROS Kinetic to ROS Noetic. 
I think the implementation of real robots should be pretty similar to the [original RRT Exploration](https://github.com/hasauino/rrt_exploration).
If you have no issue deploying the original, I think the ROS noetic one should be quite easy.

Cheers,
Billy
