### ISSUE TITLE
Running the node on real Turtlebot 3

### ISSUE THREAD

**Issue by mmsh28** [hikashi/multi-robot-rrt-exploration-noetic#3]
Hello again,
I went through the link and all the steps provided there, it was mainly on setting up the robot, and it is all setup and all packages are installed, yet when I plan to run it on the actual robot I first run the gmapping launch file, then I run the move base launch file, what launch files do I have to run next so that it works. Please find attached my rqt_graph maybe it gives you a better idea on what is missing.

![Screenshot from 2023-06-06 10-48-08](https://github.com/hikashi/multi-robot-rrt-exploration-noetic/assets/40186541/b7dd5d46-2034-45d3-8f7f-d8dc24533d6b)

**Comment by hikashi** [comment]
At a glance, it seems fine but the launch file provided here is dedicated to simulation. It would be best if you made some modifications to the original launch file to launch the robot's exploration.
I recommend comparing the TF tree and topic between the simulation and the actual robot simulation.
After that, please make sure the main ROS master is running the map merging (assuming you are not using ROS Multimaster) then it should be quite straight forward.
If you still having issue, I believe you should try the original ROS Kinetic RRT Exploration. If you having issue setting up the old version, I think this version you would encounter the same issue.
