### ISSUE TITLE
Robot not moving

### ISSUE THREAD

**Issue by ManasSashank** [hikashi/multi-robot-rrt-exploration-noetic#6]
Entered 0 of 4 to start exploration
This statement is getting printed continuously and the robot is not moving anywhere.

**Comment by hikashi** [comment]
Hi ManasSashank,

It will not autostart by default. 
The original RRT Exploration is started by inputting 5 clicked points as shown below
![instruction2](https://github.com/hikashi/multi-robot-rrt-exploration-noetic/assets/40621513/d155bc0e-778b-4aa2-818d-75ba014cd99e)
Hope this can help you kickstart your exploration.

Regards,
Billy Lau
