### ISSUE TITLE
turtlebot3 stuck at table leg and deep room during exploration

### ISSUE THREAD

**Issue by mafifkasno** [hikashi/multi-robot-rrt-exploration-noetic#8]
I try to use it at Gazebo world map and run about 30 times. Sometimes the robot stuck. May I know why turtlebot3 if it went deeper into the room for sometimes, it cannot find path planner to go to unexplored node. It also stuck at the table leg and sometimes cannot recover.

how can we improve on this? Thank you.

**Comment by hikashi** [comment]
It is kind of known problem for RRT.
